eigen_initializer_list: move required includes outside of the Eigen class
This keeps Klocwork from getting a parse error:

   eigen_initializer_list.h:30:78:Error:parse error before TOK_typeName(Scalar)