cor: switch to c++14 to c++11 to ensure Klocwork knows to compile with C++11
Klockwork doesn't pass the --enable-cxx11 flag when we turn on C++14
which lead to this parse error

    sensor_clock.h:23:29:Error:parse error before TOK_ident(noexcept)